
name: Deploy Angular to S3

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'frontend/student-portal/**'  

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: university-student-service/frontend/student-portal
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: ng build --configuration production

    - name: Deploy to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-southeast-2  
      run: |
        aws s3 sync dist/student-portal/ s3://ussfrontbucket/frontendApp/ --delete
